{% set version = "1.0.4" %}

package:
  name: pyproject-fmt-rust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt-rust/pyproject_fmt_rust-{{ version }}.tar.gz
  sha256: 7b2ab899dc37fea291e8718baee91b02397e039d7ab1f9667ae51fdabe198935

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 2

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - maturin >=1.5.1
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyproject_fmt_rust
  source_files:
    - tests
  commands:
    - pip check
    - coverage run --source=pyproject_fmt_rust -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=100
  requires:
    - coverage
    - pip
    - pytest >=8.2

about:
  summary: Format your pyproject.toml file
  home: https://pypi.org/project/pyproject-fmt-rust
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  dev_url: https://github.com/tox-dev/pyproject-fmt-rust

extra:
  recipe-maintainers:
    - bollwyvl
