{% set version = "1.1.6" %}

package:
  name: pyproject-fmt-rust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt-rust/pyproject_fmt_rust-{{ version }}.tar.gz
  sha256: 396b432d44f03ba2d757479bb4036b0dc8e71e530391f74895a2908c90b0b5c4

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.5.1                        # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - maturin >=1.5.1
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyproject_fmt_rust
  source_files:
    - tests
  commands:
    - pip check
    - coverage run --source=pyproject_fmt_rust -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=100
  requires:
    - coverage
    - pip
    - pytest >=8.2

about:
  summary: Format your pyproject.toml file
  home: https://pypi.org/project/pyproject-fmt-rust
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  dev_url: https://github.com/tox-dev/pyproject-fmt-rust

extra:
  recipe-maintainers:
    - bollwyvl
