# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.2.1
  maturin_min: "1.5.1"

package:
  name: pyproject-fmt-rust
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyproject-fmt-rust/pyproject_fmt_rust-${{ version }}.tar.gz
  sha256: ff4b41f35a1e571ae07a890269c716c202c4d832a427ad2ef488527b55a20fe2

build:
  number: 1
  python:
    version_independent: true
  # only build for the minimal python version
  skip: not (match(python, python_min ~ ".*") and is_abi3)
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - maturin >=${{ maturin_min }}
        - python
  host:
    - maturin >=${{ maturin_min }}
    - pip
    - python
  run:
    - python
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - python:
      imports: pyproject_fmt_rust
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - coverage
        - pytest >=8.2
    script:
      - coverage run --source=pyproject_fmt_rust -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=100

about:
  summary: Format your pyproject.toml file
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/pyproject-fmt-rust
  repository: https://github.com/tox-dev/pyproject-fmt-rust

extra:
  recipe-maintainers:
    - bollwyvl
